
import { SavedCitation } from "../types";

/**
 * 모든 인용 증거 자료를 Markdown 형식으로 변환
 */
export function generateEvidenceMD(savedCitations: SavedCitation[]): string {
  let md = `# Academic Evidence Inventory\n\n`;
  md += `*Generated by ScholarCite AI*\n`;
  md += `*Total Sessions: ${savedCitations.length}*\n\n---\n\n`;

  savedCitations.forEach((cit, cIdx) => {
    md += `## Session ${savedCitations.length - cIdx} (${new Date(cit.timestamp).toLocaleString()})\n\n`;
    
    cit.references.forEach((ref) => {
      md += `### [REF #${ref.id}] ${ref.title}\n`;
      md += `- **Authors**: ${ref.authors}\n`;
      md += `- **Year**: ${ref.year}\n`;
      md += `- **Journal**: ${ref.journal} [${ref.grade}]\n`;
      md += `- **Source URL**: ${ref.url}\n`;
      md += `- **Location in Paper**: ${ref.sourceSection || 'UNKNOWN'}\n\n`;
      
      md += `#### ✨ 내 문서에 생성된 문장 (Your Result Sentence)\n`;
      md += `> ${ref.relatedCitedSentence || '정보 없음'}\n\n`;

      md += `#### 📋 추출된 논문 원문 (Evidence Sentence)\n`;
      md += `> ${ref.originalSourceSentence || '정보 없음'}\n\n`;
      
      md += `#### 🔍 원문 단락 문맥 (Context)\n`;
      md += `\`\`\`text\n${ref.sourceParagraph || '정보 없음'}\n\`\`\`\n\n`;
      
      md += `#### 💡 인용 타당성 (Logical Linkage)\n`;
      md += `${ref.citationReason}\n\n`;
      md += `---\n\n`;
    });
  });

  return md;
}

/**
 * 모든 인용 증거 자료를 Word 호환 HTML(.doc) 형식으로 변환
 */
export function generateEvidenceDoc(savedCitations: SavedCitation[]): string {
  let html = `
    <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
    <head><meta charset='utf-8'><title>Evidence Inventory</title>
    <style>
      body { font-family: 'Malgun Gothic', sans-serif; line-height: 1.6; }
      h1 { color: #1e293b; border-bottom: 2px solid #334155; padding-bottom: 10px; }
      h2 { color: #4338ca; margin-top: 30px; border-left: 5px solid #4338ca; padding-left: 10px; }
      h3 { color: #0f172a; margin-top: 20px; background: #f1f5f9; padding: 5px 10px; }
      .label { font-weight: bold; color: #64748b; font-size: 0.9em; text-transform: uppercase; margin-top: 15px; }
      .result-box { background: #ecfdf5; border: 1px solid #10b981; padding: 15px; margin: 10px 0; }
      .evidence-box { background: #eef2ff; border: 1px solid #4338ca; padding: 15px; margin: 10px 0; font-style: italic; }
      .context-box { background: #fff; border: 1px dotted #cbd5e1; padding: 15px; font-size: 0.85em; color: #475569; }
      .reason { color: #059669; font-weight: 500; }
      .section-badge { background: #334155; color: white; padding: 2px 8px; font-size: 0.8em; border-radius: 4px; }
    </style>
    </head>
    <body>
    <h1>Academic Evidence Inventory</h1>
    <p>Generated by ScholarCite AI Platinum - Total Evidence Summary</p>
  `;

  savedCitations.forEach((cit, cIdx) => {
    html += `<h2>Session ${savedCitations.length - cIdx} - ${new Date(cit.timestamp).toLocaleString()}</h2>`;
    
    cit.references.forEach((ref) => {
      html += `<h3>[REF #${ref.id}] ${ref.title} <span class='section-badge'>${ref.sourceSection}</span></h3>`;
      html += `<p><strong>Authors:</strong> ${ref.authors} (${ref.year})<br/>`;
      html += `<strong>Journal:</strong> ${ref.journal} [${ref.grade}]<br/>`;
      html += `<strong>URL:</strong> <a href='${ref.url}'>${ref.url}</a></p>`;
      
      html += `<p class='label'>내 문서에 생성된 문장</p>`;
      html += `<div class='result-box'>${ref.relatedCitedSentence || '정보 없음'}</div>`;

      html += `<p class='label'>논문 내 실제 원문 문장</p>`;
      html += `<div class='evidence-box'>"${ref.originalSourceSentence || '정보 없음'}"</div>`;
      
      html += `<p class='label'>단락 문맥</p>`;
      html += `<div class='context-box'>${ref.sourceParagraph || '정보 없음'}</div>`;
      
      html += `<p class='label'>인용 타당성 논리</p>`;
      html += `<p class='reason'>${ref.citationReason}</p>`;
      html += `<hr style='border: 0; border-top: 1px solid #eee;'/>`;
    });
  });

  html += `</body></html>`;
  return html;
}
